name: build

on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
    tags: ["v*"]

jobs:

  build:

    strategy:
      matrix:
        mpi: ['mpich', 'openmpi']
        os: ['ubuntu-latest', 'macos-latest']
        precision: [128, 256, 4096, 16384]

    name: ${{ matrix.os }} ${{ matrix.mpi }} ${{ precision }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
        # with:
        #   submodules: true

      - name: install MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: build
        run: |
          cmake -S . -B build -DPRECISON=${{ matrix.precision }} -DBUILD_TESTS=ON -DSMOKE=OFF
          cd build
          make
          cd ..

      - name: run tests
        run: |
          ./build/tests -d yes

      - name: test executables
        run: |
          mpiexec -n 5 ./build/hdspin -t 6 -N ${{ matrix.precision }} -l EREM -b 2.4 --seed=123

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install python dependencies
        run: |
          pip install numpy
          pip install scipy

      - name: run postprocess
        run: |
          python3 postprocess.py

